package badsmells;

/*
 * Refactored: Divergent Change
 *
 * Original smell: one class held reporting fields, SQL fields, and CSV fields,
 * so three unrelated reasons to change all collided in the same file.
 * Refactoring applied:
 *   - Extract Class for each reason to change: ReportFormatter, SqlInsertBuilder, CsvExporter
 *   - Move related fields with their methods so each new class is cohesive
 * Behavior preserved: each method returns the same string as the original.
 */
public class DivergentChangeExample {

	static class ReportFormatter {
		private String reportTitle = "Exam Results";
		private String reportFooter = "Generated by registrar office";

		public String format(String name, int score) {
			return reportTitle + "\n" + name + ": " + score + "\n" + reportFooter;
		}
	}

	static class SqlInsertBuilder {
		private String tableName = "exam_results";
		private String databaseUrl = "jdbc:mysql://localhost:3306/school";

		public String build(String name, int score) {
			return "/* " + databaseUrl + " */ INSERT INTO " + tableName + "(name, score) VALUES ('" + name + "', "
					+ score + ")";
		}
	}

	static class CsvExporter {
		private String csvSeparator = ",";
		private boolean includeCsvHeader = true;

		public String export(String name, int score) {
			String csv = name + csvSeparator + score;
			if (includeCsvHeader) {
				return "name" + csvSeparator + "score\n" + csv;
			}
			return csv;
		}
	}

	public void clientCode() {
		ReportFormatter report = new ReportFormatter();
		SqlInsertBuilder sql = new SqlInsertBuilder();
		CsvExporter csv = new CsvExporter();

		System.out.println(report.format("Nino", 95));
		System.out.println(sql.build("Nino", 95));
		System.out.println(csv.export("Nino", 95));
	}
}
